version: "3"
services:
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27019:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8089:80'
    environment: 
      - APP_MODULE=splash_ingest.server.api:app
      - MONGO_DB_URI=mongodb://db:27017/splash
  
  poller:
    build:
      context: .
      dockerfile: Dockerfile-poller
    environment: 
      - SCICAT_BASEURL=${SCICAT_BASEURL}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - THUMBS_ROOT=${THUMBS_ROOT}
      - SPLASH_LOG_LEVEL=${SPLASH_LOG_LEVEL}
      - SCICAT_INGEST_USER=${SCICAT_INGEST_USER}
      - SCICAT_INGEST_PASSWORD=${SCICAT_INGEST_PASSWORD}
    volumes:
      - ~/data:/data
    network_mode: host


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
        - 8081:8081
    # volumes:
    #     - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    # env_file:
    #     - .env
    environment:
        ME_CONFIG_MONGODB_SERVER: db
        # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: foo
        ME_CONFIG_BASICAUTH_PASSWORD: bar
    depends_on:
        - db