version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27019:27017"
  splash_ingest:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '8089:80'
    environment: 
      - APP_MODULE=splash_ingest.server.api:app
    