FROM python:3.8

COPY ./requirements.txt /tmp/
COPY ./requirements-webservice.txt /tmp/
RUN pip install -U pip &&        pip install -r /tmp/requirements.txt &&        pip install -r /tmp/requirements-webservice.txt
COPY ./ /app
WORKDIR /app
RUN pip install .
CMD python splash_ingest_manager/poller.py