version: "3"
services:
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27019:27017"
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '8089:80'
    environment: 
      - APP_MODULE=splash_ingest.server.api:app
      - MONGO_DB_URI=mongodb://db:27017/splash
    