version: "3"
services:
  app:
    environment: 
      - MAX_WORKERS=1
    volumes: 
      - .:/app
    ports:
      - '8089:80'
    command: uvicorn splash_ingest.server.api:app --reload --port=80 --host=0.0.0.0
  poller:
    volumes:
      - ~/data:/data
      - .:/app
networks: 
  default: 
    external: 
      name: scicat
