version: "3"
services:
  db_ingest:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27019:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - '80:80'
    environment: 
      - APP_MODULE=splash_ingest.server.api:app
      - INGEST_DB_URI=${INGEST_DB_URI}
      - DATABROKER_DB_URI=${DATABROKER_DB_URI}
  
  poller:
    build:
      context: .
      dockerfile: Dockerfile-poller
    environment: 
      - INGEST_DB_URI=${INGEST_DB_URI}
      - DATABROKER_DB_URI=${DATABROKER_DB_URI}
      - THUMBS_ROOT=${THUMBS_ROOT}
      - SPLASH_LOG_LEVEL=${SPLASH_LOG_LEVEL}
      - SCICAT_BASEURL=${SCICAT_BASEURL}
      - SCICAT_INGEST_USER=${SCICAT_INGEST_USER}
      - SCICAT_INGEST_PASSWORD=${SCICAT_INGEST_PASSWORD}
    volumes:
      - ~/data:/data



  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #       - 8081:8081
  #   # volumes:
  #   #     - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
  #   # env_file:
  #   #     - .env
  #   environment:
  #       ME_CONFIG_MONGODB_SERVER: db
  #       # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #       # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #       ME_CONFIG_BASICAUTH_USERNAME: foo
  #       ME_CONFIG_BASICAUTH_PASSWORD: bar
  #   depends_on:
  #       - db